name: bili_tracker
description: "bilibili downloader"
license: GPL-3.0
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  media_kit: ^1.2.0
  media_kit_video: ^1.3.0
  media_kit_libs_video: ^1.0.6

  cupertino_icons: ^1.0.8
  ffmpeg_kit_flutter_new: ^3.0.0
  cached_network_image: ^3.4.1
  wakelock_plus: ^1.3.2
  get_it: ^8.1.0
  intl: ^0.20.2
  html: ^0.15.6
  flutter_inappwebview: ^6.1.5
  http: ^1.4.0
  crypto: ^3.0.6
  dio: ^5.8.0+1
  synchronized: ^3.4.0
  image_gallery_saver_plus: ^4.0.1
  json_serializable: any
  json_annotation: any
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  fluttertoast: ^8.2.12
  shared_preferences: ^2.5.3
  logger: ^2.6.1
  qr_flutter: ^4.1.0
  objectbox: ^4.3.0
  objectbox_flutter_libs: ^4.3.0
  url_launcher: ^6.3.2
  provider: ^6.1.5
  pull_to_refresh_flutter3: ^2.0.2
  file: ^7.0.1
  path: ^1.9.1
  screen_brightness: ^2.1.7
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  objectbox_generator: any
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  fonts:
    - family: MiSans
      fonts:
        - asset: assets/fonts/MiSans-Regular.ttf